- hosts: appsvrs
  tasks:
    - name:
      yum:
       pkg: httpd
       state: present
       update_cache: true
      become: true
    - name: start apache
      service:
       name: httpd
       state: started
      become: true
